name: fastlane-dev
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane ios build
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane ios tests
